### PR TITLE
#159053963 Create User Interface templates

### PR DESCRIPTION
**Pull request by migot01**
### What does this PR do?
Have a complete front-end design 

### Description of tasks to be completed
Have a design of all user interface feature , though non functional at this time

### How should this be manually tested?
Clone or download the repo. Navigate to the directory called UI and open any of the html file on any browser.

### Any background context you want to provide?
No

### What are the relevant Pivotal Tracker Stories?
[#159053963](https://www.pivotaltracker.com/story/show/159053963)

### Screenshots:
image

### CODE REVIEW

**Comment by alovega** [comment]
I like your design

**Comment by DennisWanjiru** [comment]
Follows convention and good use of commit message s

**Comment by artorious** [comment]
Good clean UI and easy to interact with. Hope your able to untangle your GitFlow

**Comment by mmosoroohh** [comment]
Looks great man. Simple and attractive design...

**Pull request merged**
